### ISSUE TITLE
Definifir la forma de colaborar en el proyecto

### ISSUE THREAD

**Issue by crisconru** [Respyrator/respirador#3]
Habría que fijar en el CONTRIBUTING.MD la forma de colaborar, par luego hacer un copia-pega en la docu (todo en español por ahora).
1. Forkea el repo.
2. Trabaja en la rama dev.
3. Antes de desarrollar:
    - Mira los issues y el tablero del Projects.
    - Si ves que hago falta o quieres aportar en un punto concreto, abre un issue especificando que es y para que.
   - Ponle labels / tags al issue para identificarlo.
   - Desarrolla en la rama dev de tu fork.
   - Documenta en docs lo que has hecho si es relevante en algún punto.
   - Etc
   - Haz tests
4. Antes de subir cambios a tu repo, configura el git remote con la rama dev del repo oficial y haz un pull en local.
5. Para subir cambios al repo oficial, haz un pull requests de tu rama dev a la rama dev del repo oficial
...

**Comment by crisconru** [comment]
@JJ en el [apartado de colaborar](https://respyrator.github.io/respirador/colaborar/) de la documentación he puesto un guión para pseudo-novatos. Échale un ojo a ver que te parece.

Por otro lado lo suyo es tener un fichero CONTRIBUTING.MD en plan más serio imagino. Vaya hablo desde mi inexperiencia total, y por si viene gente que entienda, imagino que irán ahí ¿Puedes encargarte tu mientras sigo redactando? Si no, haré un copia y pega más adelante.

**Comment by JJ** [comment]
Ok
