### ISSUE TITLE
Configurar la automatización de la documentación con Travis

### ISSUE THREAD

**Issue by crisconru** [Respyrator/respirador#4]
Para autodesplegar la documentación con travis hacen falta dos cosas:

1. Fichero de configuracion.
2. Variable de entorno en Travis `GITHUB_TOKEN`.

El fichero travis en principio está bien configurado para que cuando haya un cambio en master, se haga el despliegue en la rama gh-pages. Pero parece ser que no esta funcionando bien. Puede ser que la variable `GITHUB_TOKEN` esté mal configurada en Travis.

**Comment by crisconru** [comment]
Ya he configurado el problema del token, usando uno propio mio (no se porque desde organización n deja generarlo).
Aun así, Travis no me deja desplegar porque el cambio viene de un pull requests, ¿@JJ alguna idea?

**Comment by JJ** [comment]
Con los PRs Travis no te va a dejar usar los "secrets". En ese caso yo te aconsejo que te cambies a otra cosa, como GitHub Actions, donde puedes usar todos los tokens que quieras, aunque en caso de PRs tampoco te va a dejar algunas cosas (básicamente el API de GitHub)

**Comment by crisconru** [comment]
Por ahora mergeamos directamente entonces de dev a master despues de los pull requests.
Estoy a ver si puede automatizarlo en readthedocs pero estoy teniendo problemas con la plataforma. Ya he lanzado un ping a alguien que trabaja ahí a ver si se puede solucionar
